export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_TITLES_SUCCESS = 'LOAD_TITLE_SUCCESS';
export const LOAD_DEGREES_SUCCESS = 'LOAD_DEGREES_SUCCESS';
export const LOAD_POSITIONS_SUCCESS = 'LOAD_POSITIONS_SUCCESS';
export const LOAD_DEPARTMENTS_SUCCESS = 'LOAD_DEPARTMENTS_SUCCESS';
export const LOAD_ACADEMICUNIT_SUCCESS = 'LOAD_ACADEMICUNIT_SUCCESS';
export const LOAD_INSTITUTIONS_SUCCESS = 'LOAD_INSTITUTIONS_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const LOAD_ORSFUNCTIONS_SUCCESS = 'LOAD_ORSFUNCTIONS_SUCCESS';

